# -*- coding: utf-8 -*-
"""Beximco Pharmaceuticals GDR Stock Price.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gBy7oSOCwpTYb1QiBFwbyzb-u6Bawwlc
"""

import yfinance as yf

#!pip install -q streamlit

import streamlit as st

import pandas as pd

st.write(


         """
         ##Showcasing Stock price for Beximco Pharmaceuticals GDR

         """
)

tickerSymbol ='BXP'
tickerData = yf.Ticker(tickerSymbol)
tickerDF = tickerData.history(period = '1d', start='2010-9-17', end ='2023-5-31')

st.line_chart(tickerDF.Close)
st.line_chart(tickerDF.Volume)

#!npm install -g npm

#!npm install localtunnel

#streamlit run Beximco Pharmaceuticals GDR Stock Price.py &>/content/logs.txt
streamlit==1.1.0
plotly==5.1.0
